pipeline:
  build:
    image: python:2.7-alpine
    commands:
      - apk update && apk add zip
      - pip install -r requirements.txt -t .
      - zip -r -9 lambda-project-v1.zip *

  s3-publish:
    image: plugins/s3
    acl: private
    region: us-east-1
    bucket: test-bucket321123
    target: lambda-dir
    source: lambda-project-v1.zip

  deploy-lambda:
    image: omerxx/drone-lambda-plugin
    pull: true
    function_name: test-function
    s3_bucket: test-bucket321123
    file_name: lambda-dir/revenue-report-v1.zip

